project: ???
output_dir: outputs

defaults:
    - _self_
    - model: ???
    - datamodule: ???
    - logger: default
    - callback: default

  trainer:
    max_epochs: ???
    gpus: ???
    precision: 16
    log_every_n_steps: 10
    fast_dev_run: False

hydra:
    run:
        dir: ${output_dir}/${project}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    sweep:
        dir: ${output_dir}/multirun/${project}/${now:%Y-%m-%d}/${now:%H-%M-%S}