project: "masters-thesis-text-generation"
output_dir: outputs

defaults:
  - _self_
  - model: plt5
  - logger: default
  - callbacks: default
  - datamodule: csv_seq2seq_rhymes

trainer:
  max_epochs: 15
  accelerator: gpu
  devices: 1
  precision: 32
  log_every_n_steps: 10
  fast_dev_run: False

hydra:
    run:
        dir: ${output_dir}/${project}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    sweep:
        dir: ${output_dir}/multirun/${project}/${now:%Y-%m-%d}/${now:%H-%M-%S}