_target_: masterscreativity.datamodules.csv_datamodule.CSVDatamodule
model_name: ${model.model_name}
batch_size: 4
data_paths: 'E:\Python Projects\masters-computional-creativity\data\datafiles\wolnelektury\rhyming_words\v3_t5.csv'
mode: 'seq2seq'
train_val_ratio: 0.9
padding: "max_length"
truncation: "only_first"
max_length: 64
num_workers: 0